### ISSUE TITLE
Police and Mayor outfits

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonDawn.Panthera3#17]
comment "Exported from Arsenal by SGT. Soler-Crespo.R";

comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "rds_uniform_Policeman";
for "_i" from 1 to 2 do {this addItemToUniform "RH_16Rnd_9x19_CZ";};
this addHeadgear "rds_police_cap";
this addGoggles "G_Aviator";

comment "Add weapons";
this addWeapon "RH_cz75";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";

comment "Set identity";
this setFace "WhiteHead_05";
this setSpeaker "Male04ENG";

**Comment by HernandezD** [comment]
Mayor 

comment "Exported from Arsenal by PFC. Hernandez.D";

comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "rds_uniform_Functionary1";
this addGoggles "G_Squares";

comment "Add weapons";

comment "Add items";
this linkItem "tf_anprc152_1";

comment "Set identity";
this setFace "WhiteHead_14";
this setSpeaker "rhs_Male04RUS";

**Comment by rasolercrespo** [comment]
Mayor Edited

comment "Exported from Arsenal by PFC. Hernandez.D";

comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "rds_uniform_Functionary1";
this addGoggles "G_Squares";

comment "Add weapons";

comment "Add items";
this linkItem "ItemWatch";

comment "Set identity";
this setFace "WhiteHead_14";
this setSpeaker "rhs_Male04RUS";

**Comment by rasolercrespo** [comment]
The outfits are done -- I just need to implement them. Easy enough to do. I'm closing this.
