### ISSUE TITLE
Eyecandy Arsenal box

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonDawn.Panthera3#4]
This time, I would like to iron out the Eyecandy Arsenal items with Command. I will communicate with them to get me a list of permissible items to use (very specific) and implement it onto an Arsenal box. I will take the lead with this one.

**Comment by AJCStriker** [comment]
Word of advise, you could use the same command that I used for the persistence script to get the class names more easily via allMissionsObjects

Makes getting all the class names a lot easier.

**Comment by rasolercrespo** [comment]
Still have to sort this out with Viking.

**Comment by rasolercrespo** [comment]
I'll hold on this off, because of Arsenal. I can come back to this if needed.
