### ISSUE TITLE
Generate enemy convoy and attack raid

### ISSUE THREAD

**Issue by rasolercrespo** [23rd-gaming-division/OperationCrimsonDawn.Panthera3#6]
FOB Iron will get some sort of raid, for which I am not super sure of the Zen framework implementation. @AJCStriker and I can take a look at this.

**Comment by AJCStriker** [comment]
We can try achieving this using triggers with the zen framework.

**Comment by rasolercrespo** [comment]
That's probably the best way to do it, and the path of least resistance.

**Comment by rasolercrespo** [comment]
I've added the convoy and a trigger to set them off after 30 seconds, along with their unload marker. Now, how do we get the Zen framework to move them there? The trucks (not the units in them) are called truck1, truck2, truck3, truck4, btr1 and car1.

Any ideas @AJCStriker?

**Comment by rasolercrespo** [comment]
This is done, along with the mortar, and I am wetting myself...
